---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14
  channel: stable
  install_strategy: once
  always_update_cookbooks: true
  log_level: info
  client_rb:
    chef_license: accept

verifier:
  name: inspec

platforms:
  - name: centos-7.6

suites:
  - name: default
    driver:
      vm_hostname: ambari-server
      customize:
        memory: 10240
        cpus: 2
        natdnshostresolver1: "on"
      network:
        - ["forwarded_port", {guest: 3000, host: 3000, auto_correct: true}]     # ambari metrics grafana
        - ["forwarded_port", {guest: 8080, host: 8080, auto_correct: true}]     # ambari server http
        - ["forwarded_port", {guest: 8443, host: 8443, auto_correct: true}]     # ambari server https
        - ["forwarded_port", {guest: 8886, host: 8886, auto_correct: true}]     # log search solr admin ui
        - ["forwarded_port", {guest: 9060, host: 9060, auto_correct: true}]     # smartsense explorer
        - ["forwarded_port", {guest: 9090, host: 9090, auto_correct: true}]     # nifi server http
        - ["forwarded_port", {guest: 9091, host: 9091, auto_correct: true}]     # nifi server https
        - ["forwarded_port", {guest: 61310, host: 61310, auto_correct: true}]   # ambari metrics hbase info port
        - ["forwarded_port", {guest: 61888, host: 61888, auto_correct: true}]   # log search http ui
        - ["forwarded_port", {guest: 61889, host: 61889, auto_correct: true}]   # log search https ui
    run_list:
      - recipe[ambari-chef::ambari_server_prerequisites]
      - recipe[ambari-chef::ambari_server]
      - recipe[hdf-chef::hdf]
      - recipe[ambari-chef::ambari_cluster]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
